language: python
python:
  - 3.5
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
dist: trusty
sudo: required
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
services:
  - mysql
  - redis-server
  - rabbitmq
install:
- git clone https://github.com/anthill-platform/anthill-common $TRAVIS_BUILD_DIR/common
- python $TRAVIS_BUILD_DIR/common/setup.py install
- python setup.py install
script:
  - python -m anthill.common.testing
