language: python
python:
  - "2.7"
virtualenv:
    system_site_package: true
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/src:$TRAVIS_BUILD_DIR/common/src
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
dist: trusty
sudo: required
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
services:
  - mysql
  - redis-server
  - rabbitmq
cache:
  directories:
   - $TRAVIS_BUILD_DIR/v8py
install:
  - git clone https://github.com/anthill-platform/anthill-common $TRAVIS_BUILD_DIR/common
  - pip install -r $TRAVIS_BUILD_DIR/common/src/requirements.txt
  - pip install -r src/requirements.txt
script:
  - python -m common.testing
