language: python
python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
virtualenv:
    system_site_package: true
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/common
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
dist: trusty
sudo: required
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
services:
  - mysql
  - redis-server
  - rabbitmq
cache:
  directories:
   - $TRAVIS_BUILD_DIR/v8py
install:
  - git clone https://github.com/anthill-platform/anthill-common $TRAVIS_BUILD_DIR/common
  - pip install -r $TRAVIS_BUILD_DIR/common/requirements.txt
  - pip install -r requirements.txt
script:
  - python -m anthill.common.testing
